### ISSUE TITLE
ability to toggle webM

### ISSUE THREAD

**Issue by drzraf** [ThatOneGuyDotNet/QuickJava#41] opened 2016-11-17 03:12 UTC
Could be useful setting when Flash behaves better than "native" video support

**Comment by ThatOneGuyDotNet** [comment] 2016-11-19 17:04
Duplicate of #23

**Closed by ThatOneGuyDotNet** 2016-11-19 17:04 UTC

**Comment by ThatOneGuyDotNet** [comment] 2016-11-19 17:05
Also, if I decide to do #36 you will be able to handle this yourself if you wish to do so. (Still don't have time to implement that, so it may be a while if I do)
